pipeline:
  name: demo-pipeline-template
  identifier: demopipelinefromtemplate
  tags: {}
  template:
    templateRef: account.demopipelinetemplate
  projectIdentifier: default_project
  orgIdentifier: default
